inherit_gem:
  gitlab-styles:
    - rubocop-default.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2
  UseCache: true
  CacheRootDirectory: tmp
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'scripts/**/*'
    - 'log/**/*'
    - 'doc/**/*'
    - 'db/**/*'
    - 'bin/*'
    - 'Rakefile'

Rails:
  Enabled: true

# == Metrics == #
Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 10

Metrics/ClassLength:
  Max: 100

Metrics/ModuleLength:
  Max: 100

Metrics/ParameterLists:
  Max: 5

# == Layout == #
Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle:      table

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/ExtraSpacing:
  ForceEqualSignAlignment: true

Layout/Tab:
  IndentationWidth: 2

# == Style == #
Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/CollectionMethods:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/RedundantReturn:
  Enabled: false

# == Disabled Cops == #
RSpec/ContextWording:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
